executor:
  name: slurm
  submit-cmd: >
    mkdir -p logs/{rule}/ &&
    sbatch
      --nodes=1
      --cpus-per-task={threads}
      --mem={resources.mem_mb}
      --time={resources.time}
      --job-name=smk-{rule}
      --parsable
      --output=logs/{rule}/{jobid}.out
      --error=logs/{rule}/{jobid}.err
  status-cmd: ~/slurm-status.py
  jobs: 200
  default-resources:
    mem_mb: 4000
    time: 1320

# General Snakemake options
latency-wait: 30
local-cores: 8
restart-times: 1
max-jobs-per-second: 10
max-status-checks-per-second: 10
keep-going: true
rerun-incomplete: true
printshellcmds: true
scheduler: greedy
use-conda: true
conda-frontend: conda
